apiVersion: apps/v1
kind: Deployment
metadata:
  name: debug-server-deployment
  labels:
    app: debug-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debug-server
  template:
    metadata:
      labels:
        app: debug-server
    spec:
      containers:
      - name: debug-server
        image: gcr.io/kubernetes-e2e-test-images/resource-consumer:1.5
        imagePullPolicy: Always
        resources:
          requests:
            memory: "0.5Gi"
            cpu: "0.5"
          limits:
            memory: "2Gi"
            cpu: "2"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: debug-server
  labels:
    app: debug-server
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: debug-server
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: debug-server
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: debug-server-deployment
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 75
